apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: labralords-metadata-scraper-service
spec:
  selector:
    app: labralords-metadata-scraper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
