apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: production

images:
  - name: labralords.azurecr.io/labralords-access-scraper
    newTag: latest

configMapGenerator:
  - literals:
      - NODE_ENV="production"
    name: labralords-access-scraper-configmap
    namespace: production

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
secretGenerator:
  - name: database-secret
    namespace: production
    envs:
      - database-secret.env
