apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: stage

images:
  - name: labralords.azurecr.io/labralords-api
    newTag: latest

configMapGenerator:
  - literals:
      - NODE_ENV="stage"
    name: labralords-api-configmap
    namespace: stage

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
  - target:
      kind: Ingress
      name: labralords-api-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev-api.labralords.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev-api.labralords.com
      - op: replace
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1cors-allow-origin
        value: dev.labralords.com
         
  - target:
      kind: Certificate
      name: labralords-api
    patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: dev-api.labralords.com

secretGenerator:
  - name: database-secret
    namespace: production
    envs:
      - database-secret.env
