
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: stage

images:
  - name: labralords.azurecr.io/labralords-client
    newTag: latest

configMapGenerator:
  - literals:
      - NODE_ENV="stage"
    name: labralords-client-configmap
    namespace: stage

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
  - target:
      kind: Ingress
      name: labralords-client-ingress
    patch: |-
      - op: replace
        path: /spec/rules
        value:
          - host: dev.labralords.com
            http:
              paths:
              - backend:
                  service:
                    name: labralords-client-service
                    port:
                      number: 80
                path: /
                pathType: Prefix
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - dev.labralords.com
  - target:
      kind: Certificate
      name: labralords-client
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - dev.labralords.com
